# Generated by Django 4.1.4 on 2022-12-23 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_datecompleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='importand',
            new_name='important',
        ),
    ]
